[custom]

ruleset=✨ AI,https://cdn.jsdelivr.net/gh/liandu2024/clash@main/list/ChatGPT.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI2.list

; 补充域名匹配规则
;rule=DOMAIN-SUFFIX,?,🧺 补充直连
rule=DOMAIN-SUFFIX,wanmei.com,🧺 补充直连
rule=DOMAIN-SUFFIX,laohu.com,🧺 补充直连
rule=DOMAIN-KEYWORD,dji,🧺 补充直连
rule=DOMAIN-SUFFIX,dji.com,🧺 补充直连
rule=DOMAIN-KEYWORD,uugame,🧺 补充直连
rule=DOMAIN-KEYWORD,uu.163,🧺 补充直连
rule=DOMAIN-KEYWORD,uu.netease,🧺 补充直连
rule=DOMAIN-KEYWORD,tgp,🧺 补充直连
rule=DOMAIN-KEYWORD,qqgame,🧺 补充直连
rule=DOMAIN-KEYWORD,ngame.qq,🧺 补充直连
rule=DOMAIN-KEYWORD,game.qq,🧺 补充直连
rule=DOMAIN-KEYWORD,play.qq,🧺 补充直连
rule=DOMAIN-KEYWORD,ttacc.net,🧺 补充直连
rule=DOMAIN-KEYWORD,tencentyun,🧺 补充直连
rule=DOMAIN-KEYWORD,tencentaccelerator,🧺 补充直连
rule=DOMAIN-KEYWORD,txacc.tencent.com,🧺 补充直连
; 支持 Apple captive portal、Bonjour、局域网发现等服务，防止局域网设备失效
rule=DOMAIN-SUFFIX,captive.apple.com,DIRECT
rule=DOMAIN-SUFFIX,local,DIRECT
rule=DOMAIN-SUFFIX,lan,DIRECT
rule=DOMAIN-SUFFIX,internal,DIRECT
rule=IP-CIDR,224.0.0.251/32,DIRECT,no-resolve  ; mDNS 发现服务

;小直连规则（补充必要直连域）
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleCNProxyIP.list
;CDN镜像拉取
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaBank/ChinaBank.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaCloud/ChinaCloud.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaGovernment/ChinaGovernment.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaISP/ChinaISP.list
ruleset=REJECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
ruleset=REJECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@refs/heads/master/Clash/BanEasyPrivacy.list
ruleset=REJECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
;Github拉取
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
;ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaBank/ChinaBank.list
;ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaCloud/ChinaCloud.list
;ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaGovernment/ChinaGovernment.list
;ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaISP/ChinaISP.list
;ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyPrivacy.list
;ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

;Proxy Groups
custom_proxy_group=✨ AI`select`[]♻️ 所有自动`[]GPT自动`[]JMS自动`[]DIRECT`.*
custom_proxy_group=🧺 补充直连`select`[]♻️ 所有自动`[]GPT自动`[]JMS自动`[]DIRECT`.*
custom_proxy_group=🚀 节点选择`select`[]♻️ 所有自动`[]GPT自动`[]JMS自动`[]DIRECT`.*

custom_proxy_group=♻️ 所有自动`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=GPT自动`url-test`(GPT)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=JMS自动`url-test`(JMS)`http://www.gstatic.com/generate_204`300,,50

; 启动设置
enable_rule_generator=true
overwrite_original_rules=true
